name: Backend Production CD

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync changes to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
          cd /path/to/backend && git pull origin production
          docker-compose exec backend python -m pip install -r app/requirements.txt
          docker-compose up -d backend"
